name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t rishabchauhan22/okok .
    # - name: run test
    #   run: docker run rishabchauhan22/okok  npm  test -- --coverage
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ access_key.ACCESS_KEY }}
        aws_secret_key: ${{ access_key.AWS_SECRET_KEY }}
        application_name: test
        environment_name: Test-env
        version_label: Sample Application
        region: ap-southeast-1
        